c_compiler:  # [win]
  - vs2019  # [win]
c_stdlib_version:          # [osx and x86]
  - '10.13'                # [osx and x86]
channel_sources:
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main